name: Check PR Validity

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-node-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find node_modules in pull request commits
        run: |
          # Get a list of all files in the PR
          if git diff --name-only $(git merge-base HEAD origin/main) | grep -q 'node_modules'; then
            echo "node_modules directory or files detected in the PR. Please remove them before committing.";
            exit 1;
          else
            echo "No node_modules detected in this PR."
          fi
